#! /usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yujiro Shito
# SPDX-License-Identifier: BSD-3-Clause

import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

def checknum(s):
    try:
        int(s)
    except:
        print("Input Error: 不明な入力です。")
        sys.exit(1)

def calculator(formula):
    tokens = formula.split()
    if len(tokens) != 3:
        print("Error: 無効な式です。 適切な式は 1 + 2 のように入力してください。")
        sys.exit(1)

    num1, operator, num2 = tokens
    checknum(num1)
    checknum(num2)

    num1 = tonum(num1)
    num2 = tonum(num2)

    if operator == '+':
        result = num1 + num2
    elif operator == '-':
        result = num1 - num2
    elif operator == '*':
        result = num1 * num2
    elif operator == '/':
        if num2 == 0:
            print("Error: ゼロでの割り算は無効です")
            sys.exit(1)
        result = num1 / num2
    else:
        print("Error: その演算子は無効です。 適切な演算子 +, -, *, / を入力してください。")
        sys.exit(1)

    print("Result:", result)

if __name__ == "__main__":

        for line in sys.stdin:
            formula = line.rstrip()

            calculator(formula)

    
