#! /usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yujiro Shito
# SPDX-License-Identifier: BSD-3-Clause

import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

def checknum(s):
    try:
        int(s)
    except:
        print("Error")
        sys.exit(1)

first_line = sys.stdin.readline().rstrip()
checknum(first_line)
ans = tonum(first_line)

for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
